project:
  type: website
  output-dir: docs

website:
  title: "Mia Silva"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example-analysis.qmd
        text: Example Analysis

format:
  html:
    theme:
      - minty
    css: styles.css
    toc: true

editor: visual

